const endpoints = {
  API_REQ_PING: '/api/ping',
  API_REQ_LOGIN: '/api/login',
  API_REQ_CONFIG: '/api/options',
  API_REQ_REGISTRATION: '/api/user/registration',
  API_REQ_PAGE: '/api/page/:slug',
  API_REQ_POSTS: '/api/post',
  API_REQ_POST: '/api/post/:slug',
  API_REQ_PROFILE: '/api/user',
  API_REQ_PROFILE_ACTIVATE: '/api/user/activate/:hash',
  API_REQ_PROFILE_CONFIRMATION: '/api/user/confirmation/:hash',
  API_REQ_PROFILE_PRIZE: '/api/user/prize/:hash',
  API_REQ_PROFILE_FORGOT_PASSWORD: '/api/user/forgot/password',
  API_REQ_PROFILE_RESET_PASSWORD: '/api/user/reset/password',
  API_REQ_PROFILE_VOTE: '/api/user/vote',
  API_REQ_PROFILE_STATISTICS: '/api/statistics',
  API_REQ_PROFILE_IDEA: '/api/user/idea',
  API_REQ_PROFILE_DELETE: '/api/user/delete',
  API_REQ_PASSWORD: '/api/user/password',
  API_REQ_PERSONAL: '/api/user/personal',
  API_REQ_IDEA: '/api/ideas/:id',
  API_REQ_IDEAS: '/api/ideas',
  API_REQ_PROJECT: '/api/projects/:id',
  API_REQ_PROJECTS: '/api/projects',
  API_REQ_PLAN: '/api/plans/:id',
  API_REQ_PLANS: '/api/plans',
  API_REQ_MEDIA: '/api/media/:id',
  API_REQ_MEDIA_DOWNLOAD: '/api/media/download/:id',
  API_REQ_GEOCODING: '/api/geocoding',
  API_REQ_FILTER_IDEAS: '/api/idea/filter',
  API_REQ_FILTER_PROJECTS: '/api/projects/filter',
  API_REQ_FILTER_PLANS: '/api/plans/filter',
  API_REQ_VOTE_LIST: '/api/vote/list',
  API_REQ_VOTE_CHECK: '/api/vote/check/:id',
  API_REQ_VOTE_STATUS: '/api/vote/status',
  API_REQ_PHASE_CHECK: '/api/phase/check'
}

export default endpoints
