version: '3.4'

services:
  frontend:
    build:
      context: ./docker/local
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./:/app
    networks:
      - participatory

networks:
  participatory:
    name: participatory_default
    external: true
