services:
  frontend:
    build:
      context: ./docker/local
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./:/app
    networks:
      - participatory
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  participatory:
    name: participatory_default
    external: true
